/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServiceRequestsRouteImport } from './routes/_authenticated/service-requests'
import { Route as AuthenticatedProcessesRouteImport } from './routes/_authenticated/processes'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedFaqsRouteImport } from './routes/_authenticated/faqs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminWorkspaceToolsRouteImport } from './routes/_authenticated/admin.workspace-tools'
import { Route as AuthenticatedAdminTutorialsRouteImport } from './routes/_authenticated/admin.tutorials'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as AuthenticatedAdminServiceTypesRouteImport } from './routes/_authenticated/admin.service-types'
import { Route as AuthenticatedAdminServiceRequestsRouteImport } from './routes/_authenticated/admin.service-requests'
import { Route as AuthenticatedAdminProcessesRouteImport } from './routes/_authenticated/admin.processes'
import { Route as AuthenticatedAdminMeetingsRouteImport } from './routes/_authenticated/admin.meetings'
import { Route as AuthenticatedAdminKnowledgeCategoriesRouteImport } from './routes/_authenticated/admin.knowledge-categories'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated/admin.knowledge'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin.faqs'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiceRequestsRoute =
  AuthenticatedServiceRequestsRouteImport.update({
    id: '/service-requests',
    path: '/service-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessesRoute = AuthenticatedProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaqsRoute = AuthenticatedFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWorkspaceToolsRoute =
  AuthenticatedAdminWorkspaceToolsRouteImport.update({
    id: '/workspace-tools',
    path: '/workspace-tools',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTutorialsRoute =
  AuthenticatedAdminTutorialsRouteImport.update({
    id: '/tutorials',
    path: '/tutorials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServiceTypesRoute =
  AuthenticatedAdminServiceTypesRouteImport.update({
    id: '/service-types',
    path: '/service-types',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServiceRequestsRoute =
  AuthenticatedAdminServiceRequestsRouteImport.update({
    id: '/service-requests',
    path: '/service-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProcessesRoute =
  AuthenticatedAdminProcessesRouteImport.update({
    id: '/processes',
    path: '/processes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMeetingsRoute =
  AuthenticatedAdminMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKnowledgeCategoriesRoute =
  AuthenticatedAdminKnowledgeCategoriesRouteImport.update({
    id: '/knowledge-categories',
    path: '/knowledge-categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faqs': typeof AuthenticatedFaqsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/processes': typeof AuthenticatedProcessesRoute
  '/service-requests': typeof AuthenticatedServiceRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/team': typeof AuthenticatedTeamRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/knowledge-categories': typeof AuthenticatedAdminKnowledgeCategoriesRoute
  '/admin/meetings': typeof AuthenticatedAdminMeetingsRoute
  '/admin/processes': typeof AuthenticatedAdminProcessesRoute
  '/admin/service-requests': typeof AuthenticatedAdminServiceRequestsRoute
  '/admin/service-types': typeof AuthenticatedAdminServiceTypesRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/tutorials': typeof AuthenticatedAdminTutorialsRoute
  '/admin/workspace-tools': typeof AuthenticatedAdminWorkspaceToolsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faqs': typeof AuthenticatedFaqsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/processes': typeof AuthenticatedProcessesRoute
  '/service-requests': typeof AuthenticatedServiceRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/team': typeof AuthenticatedTeamRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/knowledge-categories': typeof AuthenticatedAdminKnowledgeCategoriesRoute
  '/admin/meetings': typeof AuthenticatedAdminMeetingsRoute
  '/admin/processes': typeof AuthenticatedAdminProcessesRoute
  '/admin/service-requests': typeof AuthenticatedAdminServiceRequestsRoute
  '/admin/service-types': typeof AuthenticatedAdminServiceTypesRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/tutorials': typeof AuthenticatedAdminTutorialsRoute
  '/admin/workspace-tools': typeof AuthenticatedAdminWorkspaceToolsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/faqs': typeof AuthenticatedFaqsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/processes': typeof AuthenticatedProcessesRoute
  '/_authenticated/service-requests': typeof AuthenticatedServiceRequestsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/_authenticated/admin/knowledge-categories': typeof AuthenticatedAdminKnowledgeCategoriesRoute
  '/_authenticated/admin/meetings': typeof AuthenticatedAdminMeetingsRoute
  '/_authenticated/admin/processes': typeof AuthenticatedAdminProcessesRoute
  '/_authenticated/admin/service-requests': typeof AuthenticatedAdminServiceRequestsRoute
  '/_authenticated/admin/service-types': typeof AuthenticatedAdminServiceTypesRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/tutorials': typeof AuthenticatedAdminTutorialsRoute
  '/_authenticated/admin/workspace-tools': typeof AuthenticatedAdminWorkspaceToolsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/announcements'
    | '/dashboard'
    | '/faqs'
    | '/knowledge'
    | '/learning'
    | '/meetings'
    | '/processes'
    | '/service-requests'
    | '/settings'
    | '/support'
    | '/team'
    | '/workspace'
    | '/admin/announcements'
    | '/admin/faqs'
    | '/admin/knowledge'
    | '/admin/knowledge-categories'
    | '/admin/meetings'
    | '/admin/processes'
    | '/admin/service-requests'
    | '/admin/service-types'
    | '/admin/tickets'
    | '/admin/tutorials'
    | '/admin/workspace-tools'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/announcements'
    | '/dashboard'
    | '/faqs'
    | '/knowledge'
    | '/learning'
    | '/meetings'
    | '/processes'
    | '/service-requests'
    | '/settings'
    | '/support'
    | '/team'
    | '/workspace'
    | '/admin/announcements'
    | '/admin/faqs'
    | '/admin/knowledge'
    | '/admin/knowledge-categories'
    | '/admin/meetings'
    | '/admin/processes'
    | '/admin/service-requests'
    | '/admin/service-types'
    | '/admin/tickets'
    | '/admin/tutorials'
    | '/admin/workspace-tools'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/announcements'
    | '/_authenticated/dashboard'
    | '/_authenticated/faqs'
    | '/_authenticated/knowledge'
    | '/_authenticated/learning'
    | '/_authenticated/meetings'
    | '/_authenticated/processes'
    | '/_authenticated/service-requests'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/team'
    | '/_authenticated/workspace'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/knowledge-categories'
    | '/_authenticated/admin/meetings'
    | '/_authenticated/admin/processes'
    | '/_authenticated/admin/service-requests'
    | '/_authenticated/admin/service-types'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/tutorials'
    | '/_authenticated/admin/workspace-tools'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-requests': {
      id: '/_authenticated/service-requests'
      path: '/service-requests'
      fullPath: '/service-requests'
      preLoaderRoute: typeof AuthenticatedServiceRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processes': {
      id: '/_authenticated/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AuthenticatedProcessesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faqs': {
      id: '/_authenticated/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof AuthenticatedFaqsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/workspace-tools': {
      id: '/_authenticated/admin/workspace-tools'
      path: '/workspace-tools'
      fullPath: '/admin/workspace-tools'
      preLoaderRoute: typeof AuthenticatedAdminWorkspaceToolsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tutorials': {
      id: '/_authenticated/admin/tutorials'
      path: '/tutorials'
      fullPath: '/admin/tutorials'
      preLoaderRoute: typeof AuthenticatedAdminTutorialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/service-types': {
      id: '/_authenticated/admin/service-types'
      path: '/service-types'
      fullPath: '/admin/service-types'
      preLoaderRoute: typeof AuthenticatedAdminServiceTypesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/service-requests': {
      id: '/_authenticated/admin/service-requests'
      path: '/service-requests'
      fullPath: '/admin/service-requests'
      preLoaderRoute: typeof AuthenticatedAdminServiceRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/processes': {
      id: '/_authenticated/admin/processes'
      path: '/processes'
      fullPath: '/admin/processes'
      preLoaderRoute: typeof AuthenticatedAdminProcessesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/meetings': {
      id: '/_authenticated/admin/meetings'
      path: '/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AuthenticatedAdminMeetingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/knowledge-categories': {
      id: '/_authenticated/admin/knowledge-categories'
      path: '/knowledge-categories'
      fullPath: '/admin/knowledge-categories'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRoute
  AuthenticatedAdminKnowledgeCategoriesRoute: typeof AuthenticatedAdminKnowledgeCategoriesRoute
  AuthenticatedAdminMeetingsRoute: typeof AuthenticatedAdminMeetingsRoute
  AuthenticatedAdminProcessesRoute: typeof AuthenticatedAdminProcessesRoute
  AuthenticatedAdminServiceRequestsRoute: typeof AuthenticatedAdminServiceRequestsRoute
  AuthenticatedAdminServiceTypesRoute: typeof AuthenticatedAdminServiceTypesRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminTutorialsRoute: typeof AuthenticatedAdminTutorialsRoute
  AuthenticatedAdminWorkspaceToolsRoute: typeof AuthenticatedAdminWorkspaceToolsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminKnowledgeRoute: AuthenticatedAdminKnowledgeRoute,
  AuthenticatedAdminKnowledgeCategoriesRoute:
    AuthenticatedAdminKnowledgeCategoriesRoute,
  AuthenticatedAdminMeetingsRoute: AuthenticatedAdminMeetingsRoute,
  AuthenticatedAdminProcessesRoute: AuthenticatedAdminProcessesRoute,
  AuthenticatedAdminServiceRequestsRoute:
    AuthenticatedAdminServiceRequestsRoute,
  AuthenticatedAdminServiceTypesRoute: AuthenticatedAdminServiceTypesRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminTutorialsRoute: AuthenticatedAdminTutorialsRoute,
  AuthenticatedAdminWorkspaceToolsRoute: AuthenticatedAdminWorkspaceToolsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaqsRoute: typeof AuthenticatedFaqsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedProcessesRoute: typeof AuthenticatedProcessesRoute
  AuthenticatedServiceRequestsRoute: typeof AuthenticatedServiceRequestsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaqsRoute: AuthenticatedFaqsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedProcessesRoute: AuthenticatedProcessesRoute,
  AuthenticatedServiceRequestsRoute: AuthenticatedServiceRequestsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
